### ISSUE TITLE
json_tools: reference to file on local filesystem of developer

### ISSUE THREAD

**Issue by sdemarre** [maxima-project-on-github/maxima-packages#33]
I suspect this is unintentional.
https://github.com/maxima-project-on-github/maxima-packages/blob/2f09ef485fbcb7fe2b5711c9b4b79dbf7ce0e62e/robert-dodier/json_tools/read_json.mac#L50

**Comment by robert-dodier** [comment]
Haha, yes you are right! Let me fix that.

**Comment by robert-dodier** [comment]
I have pushed 414e538 which should fix the problem. Thanks for pointing it out.
